management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: swagger-demo
  boot:
    admin:
      client:
        url: http://localhost:8180

logging:
  file: ${user.home}/swagger-demo.log