management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: swagger-demo
  boot:
    admin:
      client:
        url: http://localhost:8180

logging:
  file: ${user.home}/swagger-demo.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"