management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    git:
      enabled: true
      mode: simple
spring:
  application:
    name: swagger-demo
  boot:
    admin:
      client:
        url: http://localhost:8180

logging:
  # spring boot admin needs to know where to find the log file
  file: ${user.home}/swagger-demo.log